name: journal

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: '0 15 * * *'

jobs:
  journal:
    name: journal
    runs-on: ubuntu-18.04
    steps:
      - name: Cache source
        uses: actions/cache@v2
        with:
          path: |
            **/source
          key: ${{ runner.os }}-source-v1
      # Make sure the @v0.4.1 matches the current version of the action 
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - # run: npx learning-journal-ci archive --git git@github.com:zhbhun/learning.git --gh-token $GH_TOKEN
        run: npx learning-journal-ci changelog --git git@github.com:zhbhun/learning.git