name: journal

on:
  push:
     branches:
       - master

jobs:
  journal:
    name: journal
    runs-on: ubuntu-20.04
    steps:
      - name: Cache source
        uses: actions/cache@v2
        with:
          path: |
            **/source
          key: ${{ runner.os }}-source-v1
      # Make sure the @v0.4.1 matches the current version of the action 
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global user.email "zhbhun@gmail.com"
      - run: git config --global user.name "zhbhun"
      - run: rm -fr source
      - run: ls -al
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npx learning-journal-ci archive --git git@github.com:zhbhun/learning.git
      # - run: npx learning-journal-ci changelog --git git@github.com:zhbhun/learning.git
